// Apify YouTube Transcript Provider
// Nutzt Apify-Actors um YouTube-Transkripte + Metadaten zu holen.
// Läuft auf Apify-Infrastruktur → funktioniert auch von Hetzner.
//
// Actor-Kette, in dieser Reihenfolge:
//   1. johnvc/YoutubeTranscripts — der einzige mit echter Sprachwahl
//   2. codepoetry/youtube-transcript-ai-scraper
//   3. supreme_coder/youtube-transcript-scraper (fest Englisch)
//   4. scrape-creators/best-youtube-transcripts-scraper (ohne Sprachwahl)
//   5. Falls alle ohne Transkript bleiben: KI-Transkription über codepoetry —
//      nur mit APIFY_AI_FALLBACK=1, siehe aiFallbackAktiv()
//
// Die Reihenfolge stammt nicht aus Beliebtheit, sondern aus den
// Eingabeschemata: nur Actor 1 kann „Originalspur in Sprache X" ausdrücken.
// Actor 3 fragt fest Englisch, Actor 4 kennt gar keine Sprache — beide liefern
// für ein deutsches Video im Zweifel einen englischen Text und stehen deshalb
// hinten. Die Kette bricht erst ab, wenn ein Actor wirklich ein Transkript
// hat, nicht schon wenn einer irgendeine Antwort gibt.

import type {
  YouTubeProvider,
  TranscriptResult,
  MetadataResult,
  TranscriptSegment,
} from "./types.ts";
import { extractSegments, parseSegmentArray } from "./segments.ts";

// --- Actor Definitionen ---

interface ApifyActor {
  name: string;
  apiPath: string;
  buildInput: (
    videoURL: string,
    preferredLang: string,
    aiFallback?: boolean,
  ) => Record<string, unknown>;
  extractResult: (item: Record<string, unknown>) => ApifyResult | null;
}

interface ApifyResult {
  transcriptText: string;
  transcriptLLM: string;
  language: string;
  isAutoGenerated: boolean;
  isAIGenerated: boolean;
  error?: string;
  errorCode?: string;
}

interface ApifyMetadata {
  title: string;
  channel: string;
  channel_url: string;
  channel_id: string;
  description: string;
  duration: number;
  thumbnail: string;
  upload_date: string;
  tags: string[];
}

/**
 * Erster Feldwert, der wirklich ein nichtleerer String ist.
 *
 * Die Typprüfung ist der Zweck, nicht Beiwerk: `r.transcript` heißt bei einem
 * Actor „Fließtext", beim nächsten „Array von Segmentobjekten". Eine
 * `||`-Kette nimmt das Array als truthy an, und was dann als Transkript im
 * Dokument landete, war die Zeile
 * `[object Object],[object Object],[object Object],…` — 2549 Segmente lang,
 * mit `content.length` = 2549, was wie eine plausible Zeichenzahl aussieht.
 * Der Import lief dabei ohne jede Warnung durch.
 */
function textAus(r: Record<string, unknown>, felder: string[]): string {
  for (const f of felder) {
    const v = r[f];
    if (typeof v === "string" && v.trim() !== "") return v;
  }
  return "";
}

function buildLanguageList(preferredLang: string): string[] {
  const langs = ["de", "en"];
  if (
    preferredLang &&
    preferredLang.toLowerCase() !== "de" &&
    preferredLang.toLowerCase() !== "en"
  ) {
    langs.unshift(preferredLang);
  } else if (preferredLang?.toLowerCase() === "en") {
    langs[0] = "en";
    langs[1] = "de";
  }
  return langs;
}

/**
 * Zusätzlich angeforderte Ausgabeformate. `srt` ist die Zeitmarkenquelle: der
 * Actor liefert sie ohnehin, sie wurden bisher nur nicht angefordert.
 *
 * Ein Actor, dessen Eingabeschema diesen Wert nicht kennt, antwortet mit
 * HTTP 400. Deshalb wird in `callActor` bei genau diesem Fehler ein zweites Mal
 * ohne die Erweiterung gefragt — der Import kann dadurch nicht schlechter
 * ausgehen als vorher, höchstens ohne Zeitmarken.
 */
const ZEITFORMATE = ["srt"];

/**
 * Feldnamen, unter denen die Rückfall-Actors den Transkripttext führen.
 *
 * `transcript_only_text` steht vorn und ist der Grund für diese Liste:
 * scrape-creators legt dort den Fließtext ab (117 000 Zeichen für ein
 * anderthalbstündiges Video) und unter `transcript` die Segmente. Wer
 * `transcript` zuerst liest, bekommt das Array.
 */
const TEXT_FELDER = [
  "non_timestamped",
  "transcript_only_text",
  "transcript_text",
  "text",
  "transcript",
  "content",
];

const ACTOR_CHAIN: ApifyActor[] = [
  {
    /**
     * Erster Actor, weil er der einzige geprüfte ist, der die eigentliche
     * Anforderung ausdrücken kann: „gib mir die Originalspur in dieser
     * Sprache".
     *
     * `languages` ist eine Prioritätsliste über die Originalspuren,
     * `translate_to` ein davon *getrenntes* Feld. Genau diese Trennung fehlte
     * den vorher benutzten Actors: scrape-creators kennt keine Sprachwahl und
     * lieferte für ein deutsches Gespräch die englische Spur. `translate_to`
     * wird hier bewusst nie gesetzt — eine Übersetzung ist kein Transkript.
     *
     * Ein Aufruf liefert Transkript, Zeitmarken (`timestamped`, immer dabei)
     * und die vollständigen Metadaten inklusive `upload_date` und `tags`.
     */
    name: "johnvc/YoutubeTranscripts",
    apiPath: "johnvc~YoutubeTranscripts",
    buildInput: (videoURL, preferredLang) => ({
      youtube_url: videoURL,
      languages: buildLanguageList(preferredLang),
      // "any" statt "generated": wo es von Hand erstellte Untertitel gibt,
      // sind die besser als die maschinellen.
      transcript_type: "any",
      include_metadata: true,
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      // Der Actor kennzeichnet den Fehlschlag über `success`, nicht über ein
      // Fehlerfeld allein.
      if (r.success === false) {
        return {
          transcriptText: "",
          transcriptLLM: "",
          language: "",
          isAutoGenerated: false,
          isAIGenerated: false,
          error: textAus(r, ["error", "message"]) || "unbekannter Fehler",
          errorCode: textAus(r, ["error_code"]),
        };
      }
      return {
        transcriptText: textAus(r, ["non_timestamped", "text"]),
        transcriptLLM: "",
        language: textAus(r, ["language_code"]),
        isAutoGenerated:
          r.is_generated === true ||
          textAus(r, ["source_type"]).toLowerCase().includes("auto"),
        isAIGenerated: false,
      };
    },
  },
  {
    name: "codepoetry/youtube-transcript-ai-scraper",
    apiPath: "codepoetry~youtube-transcript-ai-scraper",
    buildInput: (videoURL, preferredLang, aiFallback = false) => ({
      startUrls: [{ url: videoURL }],
      languages: buildLanguageList(preferredLang),
      outputFormats: ["text", "llm", ...ZEITFORMATE],
      enableAiFallback: aiFallback,
      // Nur mitgeben, wenn der Rückfall wirklich gemeint ist — sonst stünden
      // KI-Grenzen in einem Aufruf, der keine KI benutzt.
      ...(aiFallback
        ? {
            // Beide Grenzen ausdrücklich: der Actor käme sonst mit seinem
            // Vorgabewert maxAiMinutes=30 und würde ein längeres Video
            // *anfangen* und mitten drin abbrechen — bezahlt, ohne Ergebnis.
            // `skipAiFallbackIfLongerThan` lässt ihn stattdessen von
            // vornherein ablehnen.
            maxAiMinutes: aiMaxMinuten(),
            skipAiFallbackIfLongerThan: aiMaxMinuten(),
          }
        : {}),
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      if (r.error && r.error !== "") {
        return {
          transcriptText: "",
          transcriptLLM: "",
          language: "",
          isAutoGenerated: false,
          isAIGenerated: false,
          error: r.error as string,
          errorCode: (r.error_code as string) || "",
        };
      }
      return {
        transcriptText: textAus(r, ["transcript_text"]),
        transcriptLLM: textAus(r, ["transcript_llm"]),
        language: textAus(r, ["language"]),
        isAutoGenerated: !!(r.is_auto_generated as boolean),
        isAIGenerated: !!(r.is_ai_generated as boolean),
      };
    },
  },
  {
    name: "supreme_coder/youtube-transcript-scraper",
    apiPath: "supreme_coder~youtube-transcript-scraper",
    // `urls` ist bei diesem Actor eine requestListSources-Liste, also Objekte
    // mit `url` — nicht die nackten Strings, die hier standen. Der Actor
    // antwortete deshalb ausnahmslos mit HTTP 400 ("Items in input.urls at
    // positions [0] do not match"), womit der erste Rückfall der Kette nie
    // funktioniert hat. Geprüft am Eingabeschema des Builds.
    //
    // outputFormat bleibt "text" (erlaubt sind json|text|vtt|srt): das ist
    // das Format, aus dem extractResult unten Text lesen kann. "json" oder
    // "srt" brächten Zeitmarken mit, aber die Feldnamen dieses Actors sind
    // ungeprüft — ein Transkript ohne Zeitmarken ist besser als keines.
    buildInput: (videoURL) => ({
      urls: [{ url: videoURL }],
      outputFormat: "text",
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      const text = textAus(r, TEXT_FELDER);
      return {
        transcriptText: text,
        transcriptLLM: "",
        language: textAus(r, ["language", "lang"]),
        isAutoGenerated: !!(r.is_auto_generated as boolean),
        isAIGenerated: !!(r.is_ai_generated as boolean),
        error: r.error as string | undefined,
        errorCode: r.error_code as string | undefined,
      };
    },
  },
  {
    name: "scrape-creators/best-youtube-transcripts-scraper",
    apiPath: "scrape-creators~best-youtube-transcripts-scraper",
    // Das Pflichtfeld heißt `videoUrls`, nicht `urls`. Auch dieser Actor hat
    // deshalb nur HTTP 400 geliefert ("Field input.videoUrls is required") —
    // der zweite Rückfall war ebenso wirkungslos wie der erste.
    buildInput: (videoURL) => ({
      videoUrls: [videoURL],
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      const text = textAus(r, TEXT_FELDER);
      return {
        transcriptText: text,
        transcriptLLM: "",
        language: textAus(r, ["language", "lang"]),
        isAutoGenerated: !!(r.is_auto_generated as boolean),
        isAIGenerated: !!(r.is_ai_generated as boolean),
        error: r.error as string | undefined,
        errorCode: r.error_code as string | undefined,
      };
    },
  },
];

/**
 * Der Actor für den AI-Rückfall.
 *
 * Er wird *namentlich* gesucht und nicht als `ACTOR_CHAIN[0]` genommen:
 * `enableAiFallback` ist eine Eigenheit genau dieses Actors. Als die Kette
 * einen neuen ersten Actor bekam, hätte `ACTOR_CHAIN[0]` still auf einen
 * Actor gezeigt, der dieses Feld nicht kennt — der „AI-Rückfall" wäre ein
 * zweiter, identischer und trotzdem berechneter Aufruf des ersten Actors
 * geworden.
 */
const AI_ACTOR =
  ACTOR_CHAIN.find((a) => a.name.startsWith("codepoetry/")) ?? ACTOR_CHAIN[0];

// --- ApifyProvider ---

const APIFY_BASE = "https://api.apify.com/v2/acts";
const ACTOR_TIMEOUT = 120_000; // 2 Minuten pro Actor

/**
 * KI-Transkription als letzter Ausweg — standardmäßig **aus**.
 *
 * Sie war bisher immer aktiv und konnte praktisch nie zu einem Ergebnis
 * führen: `run-sync-get-dataset-items` gibt nach ACTOR_TIMEOUT auf, und in
 * zwei Minuten transkribiert niemand ein anderthalbstündiges Gespräch. Der
 * Actor rechnet die begonnenen KI-Minuten trotzdem ab. Beim Video, das diese
 * Untersuchung ausgelöst hat, lief der Rückfall zweimal ins Leere.
 *
 * Aus wird sie nicht deshalb, weil sie nichts taugt, sondern weil sie in einem
 * HTTP-Request nicht zu Ende laufen kann. Wer sie will, schaltet sie über
 * APIFY_AI_FALLBACK=1 ein — dann gilt aiMaxMinuten() als harte Grenze, und
 * längere Videos lehnt der Actor von vornherein ab statt sie anzufangen.
 *
 * Der reguläre Weg braucht sie nicht mehr: johnvc/YoutubeTranscripts holt die
 * vorhandenen Untertitelspuren, und Videos ohne jede Spur sind der seltene
 * Fall, für den ein Fehlschlag die ehrlichere Antwort ist.
 */
function aiFallbackAktiv(): boolean {
  return process.env.APIFY_AI_FALLBACK === "1";
}

/**
 * Obergrenze für die KI-Transkription in Minuten. Bewusst knapp unter dem, was
 * ACTOR_TIMEOUT hergeben kann — eine Grenze, die das Timeout überschreitet,
 * ist keine.
 *
 * Wie aiFallbackAktiv() zur Laufzeit gelesen und nicht beim Import: eine
 * Konstante hier wäre für Tests unerreichbar und ließe sich im Betrieb nicht
 * umstellen, ohne den Prozess neu zu starten.
 */
function aiMaxMinuten(): number {
  return Number(process.env.APIFY_AI_MAX_MINUTES ?? 10);
}

export class ApifyProvider implements YouTubeProvider {
  readonly name = "apify";
  private apiKey: string;
  private lastActorName = "";

  constructor(apiKey: string) {
    if (!apiKey) throw new Error("APIFY_API_KEY is required");
    this.apiKey = apiKey;
  }

  /** Ruft einen einzelnen Apify Actor auf und gibt die Dataset-Items zurück */
  private async callActor(
    actor: ApifyActor,
    videoURL: string,
    preferredLang: string,
    aiFallback = false,
    ohneZeitformate = false,
  ): Promise<Record<string, unknown>[]> {
    const input = actor.buildInput(videoURL, preferredLang, aiFallback);

    // Zweiter Versuch nach einem 400: die Zeitformate wieder herausnehmen.
    if (ohneZeitformate && Array.isArray((input as any).outputFormats)) {
      (input as any).outputFormats = (
        (input as any).outputFormats as string[]
      ).filter((f) => !ZEITFORMATE.includes(f));
    }

    const fullUrl = `${APIFY_BASE}/${actor.apiPath}/run-sync-get-dataset-items?token=${this.apiKey}`;

    // Nur die ersten 8 Zeichen des API-Keys im Log zeigen
    const maskedUrl = fullUrl.replace(
      this.apiKey,
      this.apiKey.slice(0, 8) + "...",
    );
    console.log(`[apify]   → POST ${actor.name} (${ACTOR_TIMEOUT}ms timeout)`);
    console.log(`[apify]   URL: ${maskedUrl}`);
    console.log(
      `[apify]   Input: languages=${JSON.stringify((input as any).languages || (input as any).urls?.length + " URLs")}`,
    );

    const t0 = Date.now();
    const response = await fetch(fullUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
      signal: AbortSignal.timeout(ACTOR_TIMEOUT),
    });

    const elapsed = Date.now() - t0;

    if (!response.ok) {
      const body = await response.text().catch(() => "");
      console.log(
        `[apify]   ❌ HTTP ${response.status} nach ${elapsed}ms: ${body.slice(0, 120)}`,
      );

      // Der Actor kennt "srt" nicht → einmal ohne erneut fragen. Ohne diesen
      // Rückfall würde ein Actor mit striktem Eingabeschema durch die neu
      // angeforderten Zeitmarken komplett ausfallen.
      const eingabefehler =
        response.status === 400 &&
        !ohneZeitformate &&
        Array.isArray((input as any).outputFormats);
      if (eingabefehler) {
        console.log(
          `[apify]   ↩︎ ${actor.name} lehnt die Zeitformate ab – erneut ohne`,
        );
        return await this.callActor(
          actor,
          videoURL,
          preferredLang,
          aiFallback,
          true,
        );
      }

      throw new Error(
        `Apify ${actor.name}: HTTP ${response.status} – ${body.slice(0, 200)}`,
      );
    }

    console.log(`[apify]   ✅ HTTP 200 nach ${elapsed}ms, lese Body...`);
    const items = (await response.json()) as Record<string, unknown>[];
    console.log(`[apify]   → ${items.length} Items erhalten`);
    return items;
  }

  /**
   * Zeitmarken aus der Actor-Antwort holen.
   *
   * Zwei Wege, weil die Actors sich hier unterscheiden: die einen legen die
   * Segmente als Feld *in* das erste Item, die anderen geben je Segment ein
   * eigenes Dataset-Item aus. Der zweite Fall wäre bei einem Blick nur auf
   * `items[0]` unsichtbar.
   */
  private segmenteAus(
    items: Record<string, unknown>[],
    durationSec?: number,
  ): TranscriptSegment[] {
    if (items.length === 0) return [];

    const imItem = extractSegments(items[0], durationSec);
    if (imItem.length > 0) return imItem;

    // Ein Item je Segment: die Item-Liste selbst ist das Segment-Array.
    return parseSegmentArray(items, durationSec);
  }

  // ---- Kombinierter Call (ein Actor-Aufruf für beides) ----

  async fetchVideoInfo(
    videoId: string,
    preferredLang = "de",
  ): Promise<import("../youtube/types.ts").VideoInfoResult> {
    const videoURL = `https://www.youtube.com/watch?v=${videoId}`;
    const startTime = Date.now();
    console.log(`[apify] ========== fetchVideoInfo START ==========`);
    console.log(`[apify] Video: ${videoURL}`);
    console.log(`[apify] Sprache: ${preferredLang}`);
    console.log(
      `[apify] Actor-Chain: ${ACTOR_CHAIN.length} Actors, ${ACTOR_TIMEOUT}ms Timeout pro Actor`,
    );

    /**
     * Metadaten des ersten Actors, der welche liefert.
     *
     * Sie müssen die Schleife überleben, weil Transkript und Metadaten nicht
     * mehr vom selben Actor kommen müssen: Actor #1 liefert oft saubere
     * Metadaten und *kein* Transkript, ein späterer dann das Transkript ohne
     * Metadaten. Vorher endete die Suche beim ersten Actor mit Items, und was
     * er nicht hatte, fehlte im Dokument.
     */
    let besteMeta: MetadataResult | null = null;

    // Alle Actors der Reihe nach durchprobieren
    for (let i = 0; i < ACTOR_CHAIN.length; i++) {
      const actor = ACTOR_CHAIN[i];
      const actorStart = Date.now();
      try {
        console.log(
          `[apify] --- Actor ${i + 1}/${ACTOR_CHAIN.length}: ${actor.name} ---`,
        );
        const items = await this.callActor(actor, videoURL, preferredLang);
        const actorElapsed = Date.now() - actorStart;
        console.log(
          `[apify] Actor ${actor.name} antwortete nach ${actorElapsed}ms, ${items.length} Items`,
        );

        if (items.length === 0) {
          console.log(
            `[apify] Actor ${actor.name}: Keine Items → nächster Actor`,
          );
          continue;
        }

        console.log(`[apify] Actor ${actor.name}: Ersten Item verarbeiten...`);
        console.log(
          `[apify] Item-Keys: ${Object.keys(items[0] as object).join(", ")}`,
        );

        // Metadaten aus dem ersten Item extrahieren
        const meta = this.extractMetadata(items);
        if (meta) {
          console.log(
            `[apify] Metadaten gefunden: "${meta.title}" (${meta.channelName})`,
          );
          besteMeta ??= meta;
        } else {
          console.log(`[apify] Keine Metadaten extrahierbar`);
        }

        // Welche Untertitelspuren der Actor überhaupt gesehen hat. Steht in der
        // Antwort und war bisher nicht im Log — genau die Angabe, an der sich
        // "Video hat keine Untertitel" von "Actor kam nicht an sie heran"
        // unterscheiden lässt.
        const sprachen = items[0]?.available_languages;
        if (sprachen !== undefined) {
          console.log(
            `[apify] Verfügbare Spuren laut Actor: ${JSON.stringify(sprachen)}`,
          );
        }

        // Transcript aus dem ersten Item extrahieren
        const result = actor.extractResult(items[0]);
        let transcript: import("../youtube/types.ts").TranscriptResult | null =
          null;
        if (result && !result.error) {
          const content = result.transcriptLLM || result.transcriptText;
          if (content) {
            this.lastActorName = actor.name;
            const source = result.isAIGenerated
              ? "ai_generated"
              : result.isAutoGenerated
                ? "auto_generated"
                : "native";
            const segments = this.segmenteAus(items, meta?.duration);
            transcript = {
              content,
              language: result.language || "unknown",
              source: source as "native" | "auto_generated" | "ai_generated",
              segments,
            };
            console.log(
              `[apify] ✅ Transkript gefunden: ${content.length} Zeichen (${result.language}, Quelle: ${source})`,
            );
            console.log(
              segments.length > 0
                ? `[apify] ✅ Zeitmarken: ${segments.length} Segmente, bis ${Math.round((segments.at(-1)!.start_ms ?? 0) / 1000)}s`
                : `[apify] ⚠️ Keine Zeitmarken in der Antwort von ${actor.name}`,
            );
          } else {
            console.log(
              `[apify] Actor ${actor.name}: Ergebnis hat keinen Text`,
            );
          }
        } else if (result?.error) {
          console.log(
            `[apify] Actor ${actor.name}: Ergebnis-Fehler: ${result.error}`,
          );
        } else {
          console.log(`[apify] Actor ${actor.name}: Kein Ergebnis`);
        }

        // Nur mit Transkript ist die Suche zu Ende. Vorher stand hier ein
        // unbedingtes `return`: ein Actor, der Metadaten und einen Fehler
        // lieferte ("No captions found"), beendete die Kette, und die zwei
        // weiteren Actors samt AI-Rückfall kamen nie zum Einsatz. Das Dokument
        // entstand dann mit Titel und Kanal, aber ohne einen Satz Transkript.
        if (transcript) {
          return { metadata: besteMeta, transcript };
        }
        console.log(
          `[apify] Actor ${actor.name}: kein Transkript → nächster Actor`,
        );
        continue;
      } catch (e: any) {
        const actorElapsed = Date.now() - actorStart;
        console.log(
          `[apify] ❌ Actor ${actor.name} fehlgeschlagen nach ${actorElapsed}ms: ${e.message?.slice(0, 150)}`,
        );
        continue;
      }
    }

    if (!aiFallbackAktiv()) {
      console.log(
        `[apify] Alle ${ACTOR_CHAIN.length} Actors ohne Transkript – AI-Rückfall ist aus (APIFY_AI_FALLBACK=1 schaltet ihn ein)`,
      );
      return { metadata: besteMeta, transcript: null };
    }

    console.log(
      `[apify] Alle ${ACTOR_CHAIN.length} Actors fehlgeschlagen, versuche AI-Fallback (max ${aiMaxMinuten()} min)...`,
    );
    // AI-Fallback mit dem Actor, der ihn kann
    try {
      const t0 = Date.now();
      console.log(
        `[apify] AI-Fallback mit ${AI_ACTOR.name} (enableAiFallback=true)...`,
      );
      const items = await this.callActor(
        AI_ACTOR,
        videoURL,
        preferredLang,
        true,
      );
      console.log(
        `[apify] AI-Fallback antwortete nach ${Date.now() - t0}ms, ${items.length} Items`,
      );
      if (items.length > 0) {
        const meta = this.extractMetadata(items) ?? besteMeta;
        const result = AI_ACTOR.extractResult(items[0]);
        let transcript: import("../youtube/types.ts").TranscriptResult | null =
          null;
        if (result && !result.error) {
          const content = result.transcriptLLM || result.transcriptText;
          if (content) {
            this.lastActorName = `${AI_ACTOR.name}(ai-fallback)`;
            transcript = {
              content,
              language: result.language || "unknown",
              source: "ai_generated",
              segments: this.segmenteAus(items, meta?.duration),
            };
            console.log(
              `[apify] ✅ AI-Fallback Transkript: ${content.length} Zeichen`,
            );
          }
        }
        return { metadata: meta, transcript };
      }
    } catch (e: any) {
      console.log(
        `[apify] ❌ AI-Fallback fehlgeschlagen: ${e.message?.slice(0, 150)}`,
      );
    }

    // Metadaten mitgeben, auch wenn kein Transkript zu holen war: der Aufrufer
    // unterscheidet daran ein Video ohne Untertitel von einem Video, das gar
    // nicht erreichbar war.
    console.log(
      `[apify] ========== fetchVideoInfo OHNE TRANSKRIPT (${Date.now() - startTime}ms) ==========`,
    );
    return { metadata: besteMeta, transcript: null };
  }

  // ---- Metadata ----

  async fetchMetadata(videoId: string): Promise<MetadataResult | null> {
    const videoURL = `https://www.youtube.com/watch?v=${videoId}`;

    // Schritt 1: Normale Actor-Chain
    for (const actor of ACTOR_CHAIN) {
      try {
        const items = await this.callActor(actor, videoURL, "");
        const meta = this.extractMetadata(items);
        if (meta) {
          this.lastActorName = actor.name;
          return meta;
        }
      } catch {
        continue;
      }
    }

    // Schritt 2: AI-Fallback mit dem Actor, der ihn kann
    if (!aiFallbackAktiv()) return null;
    try {
      const items = await this.callActor(AI_ACTOR, videoURL, "", true);
      const meta = this.extractMetadata(items);
      if (meta) {
        this.lastActorName = `${AI_ACTOR.name}(ai-fallback)`;
        return meta;
      }
    } catch {
      // nichts
    }

    return null;
  }

  private extractMetadata(
    items: Record<string, unknown>[],
  ): MetadataResult | null {
    if (items.length === 0) return null;

    const item = items[0];

    // Direktes Metadata-Format (codepoetry actor)
    const meta = item.metadata as Record<string, unknown> | undefined;
    const source = meta || item;

    const title = textAus(source, ["title"]);
    if (!title) return null;

    // Zwei Feldnamen je Angabe, weil die Actors sich hier unterscheiden:
    // codepoetry sagt `channel`/`duration`/`thumbnail`, johnvc sagt
    // `channel_name`/`video_duration_seconds`/`thumbnail_url`. Wer nur die
    // erste Form kennt, verliert beim zweiten Actor Kanal und Dauer — also
    // genau die Spalten, über die Verzeichnis und Filter gehen.
    const zahl = (...felder: string[]): number => {
      for (const f of felder) {
        const v = source[f];
        if (typeof v === "number" && Number.isFinite(v)) return v;
      }
      return 0;
    };

    return {
      videoId: "",
      title,
      channelName: textAus(source, ["channel", "channel_name"]),
      channelUrl: textAus(source, ["channel_url"]),
      duration: zahl("duration", "video_duration_seconds"),
      thumbnailUrl: textAus(source, ["thumbnail", "thumbnail_url"]),
      description: textAus(source, ["description"]),
      publishedAt: textAus(source, ["upload_date"]),
      tags: Array.isArray(source.tags)
        ? (source.tags as unknown[]).filter(
            (t): t is string => typeof t === "string",
          )
        : [],
    };
  }

  // ---- Transcript ----

  async fetchTranscript(
    videoId: string,
    preferredLang = "de",
  ): Promise<TranscriptResult | null> {
    const videoURL = `https://www.youtube.com/watch?v=${videoId}`;
    let lastError: Error | null = null;

    // Schritt 1: Normale Actor-Chain
    for (const actor of ACTOR_CHAIN) {
      try {
        const items = await this.callActor(actor, videoURL, preferredLang);
        if (items.length === 0) continue;

        const result = actor.extractResult(items[0]);
        if (!result) continue;
        if (result.error) {
          lastError = new Error(`${actor.name}: ${result.error}`);
          continue;
        }

        const content = result.transcriptLLM || result.transcriptText;
        if (!content) continue;

        this.lastActorName = actor.name;
        const source = result.isAIGenerated
          ? "ai_generated"
          : result.isAutoGenerated
            ? "auto_generated"
            : "native";

        return {
          content,
          language: result.language || "unknown",
          source: source as TranscriptResult["source"],
          segments: this.segmenteAus(items),
        };
      } catch (e: any) {
        lastError = e;
        continue;
      }
    }

    // Schritt 2: AI-Fallback mit dem Actor, der ihn kann
    if (!aiFallbackAktiv()) return null;
    try {
      const items = await this.callActor(
        AI_ACTOR,
        videoURL,
        preferredLang,
        true,
      );
      if (items.length > 0) {
        const result = AI_ACTOR.extractResult(items[0]);
        if (result && !result.error) {
          const content = result.transcriptLLM || result.transcriptText;
          if (content) {
            this.lastActorName = `${AI_ACTOR.name}(ai-fallback)`;
            return {
              content,
              language: result.language || "unknown",
              source: "ai_generated",
              segments: this.segmenteAus(items),
            };
          }
        }
      }
    } catch {
      // nichts
    }

    return null;
  }
}
