// Apify YouTube Transcript Provider
// Nutzt Apify-Actors um YouTube-Transkripte + Metadaten zu holen.
// Läuft auf Apify-Infrastruktur → funktioniert auch von Hetzner.
//
// Actor-Fallback-Chain (wie WeKnora):
//   1. codepoetry/youtube-transcript-ai-scraper (mit AI-Fallback)
//   2. supreme_coder/youtube-transcript-scraper
//   3. scrape-creators/best-youtube-transcripts-scraper
//   4. Falls alle fehlschlagen: Actor #1 mit enableAiFallback=true

import type {
  YouTubeProvider,
  TranscriptResult,
  MetadataResult,
} from "./types.ts";

// --- Actor Definitionen ---

interface ApifyActor {
  name: string;
  apiPath: string;
  buildInput: (
    videoURL: string,
    preferredLang: string,
    aiFallback?: boolean,
  ) => Record<string, unknown>;
  extractResult: (item: Record<string, unknown>) => ApifyResult | null;
}

interface ApifyResult {
  transcriptText: string;
  transcriptLLM: string;
  language: string;
  isAutoGenerated: boolean;
  isAIGenerated: boolean;
  error?: string;
  errorCode?: string;
}

interface ApifyMetadata {
  title: string;
  channel: string;
  channel_url: string;
  channel_id: string;
  description: string;
  duration: number;
  thumbnail: string;
  upload_date: string;
  tags: string[];
}

function buildLanguageList(preferredLang: string): string[] {
  const langs = ["de", "en"];
  if (
    preferredLang &&
    preferredLang.toLowerCase() !== "de" &&
    preferredLang.toLowerCase() !== "en"
  ) {
    langs.unshift(preferredLang);
  } else if (preferredLang?.toLowerCase() === "en") {
    langs[0] = "en";
    langs[1] = "de";
  }
  return langs;
}

const ACTOR_CHAIN: ApifyActor[] = [
  {
    name: "codepoetry/youtube-transcript-ai-scraper",
    apiPath: "codepoetry~youtube-transcript-ai-scraper",
    buildInput: (videoURL, preferredLang, aiFallback = false) => ({
      startUrls: [{ url: videoURL }],
      languages: buildLanguageList(preferredLang),
      outputFormats: ["text", "llm"],
      enableAiFallback: aiFallback,
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      if (r.error && r.error !== "") {
        return {
          transcriptText: "",
          transcriptLLM: "",
          language: "",
          isAutoGenerated: false,
          isAIGenerated: false,
          error: r.error as string,
          errorCode: (r.error_code as string) || "",
        };
      }
      return {
        transcriptText: (r.transcript_text as string) || "",
        transcriptLLM: (r.transcript_llm as string) || "",
        language: (r.language as string) || "",
        isAutoGenerated: !!(r.is_auto_generated as boolean),
        isAIGenerated: !!(r.is_ai_generated as boolean),
      };
    },
  },
  {
    name: "supreme_coder/youtube-transcript-scraper",
    apiPath: "supreme_coder~youtube-transcript-scraper",
    buildInput: (videoURL) => ({
      urls: [videoURL],
      outputFormat: "text",
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      const text =
        (r.transcript_text as string) ||
        (r.text as string) ||
        (r.transcript as string) ||
        (r.content as string) ||
        "";
      return {
        transcriptText: text,
        transcriptLLM: "",
        language: (r.language as string) || (r.lang as string) || "",
        isAutoGenerated: !!(r.is_auto_generated as boolean),
        isAIGenerated: !!(r.is_ai_generated as boolean),
        error: r.error as string | undefined,
        errorCode: r.error_code as string | undefined,
      };
    },
  },
  {
    name: "scrape-creators/best-youtube-transcripts-scraper",
    apiPath: "scrape-creators~best-youtube-transcripts-scraper",
    buildInput: (videoURL) => ({
      urls: [videoURL],
    }),
    extractResult: (item) => {
      const r = item as Record<string, unknown>;
      const text =
        (r.transcript_text as string) ||
        (r.text as string) ||
        (r.transcript as string) ||
        (r.content as string) ||
        "";
      return {
        transcriptText: text,
        transcriptLLM: "",
        language: (r.language as string) || (r.lang as string) || "",
        isAutoGenerated: !!(r.is_auto_generated as boolean),
        isAIGenerated: !!(r.is_ai_generated as boolean),
        error: r.error as string | undefined,
        errorCode: r.error_code as string | undefined,
      };
    },
  },
];

// --- ApifyProvider ---

const APIFY_BASE = "https://api.apify.com/v2/acts";
const ACTOR_TIMEOUT = 120_000; // 2 Minuten pro Actor

export class ApifyProvider implements YouTubeProvider {
  readonly name = "apify";
  private apiKey: string;
  private lastActorName = "";

  constructor(apiKey: string) {
    if (!apiKey) throw new Error("APIFY_API_KEY is required");
    this.apiKey = apiKey;
  }

  /** Ruft einen einzelnen Apify Actor auf und gibt die Dataset-Items zurück */
  private async callActor(
    actor: ApifyActor,
    videoURL: string,
    preferredLang: string,
    aiFallback = false,
  ): Promise<Record<string, unknown>[]> {
    const input = actor.buildInput(videoURL, preferredLang, aiFallback);
    const fullUrl = `${APIFY_BASE}/${actor.apiPath}/run-sync-get-dataset-items?token=${this.apiKey}`;

    // Nur die ersten 8 Zeichen des API-Keys im Log zeigen
    const maskedUrl = fullUrl.replace(
      this.apiKey,
      this.apiKey.slice(0, 8) + "...",
    );
    console.log(`[apify]   → POST ${actor.name} (${ACTOR_TIMEOUT}ms timeout)`);
    console.log(`[apify]   URL: ${maskedUrl}`);
    console.log(
      `[apify]   Input: languages=${JSON.stringify((input as any).languages || (input as any).urls?.length + " URLs")}`,
    );

    const t0 = Date.now();
    const response = await fetch(fullUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
      signal: AbortSignal.timeout(ACTOR_TIMEOUT),
    });

    const elapsed = Date.now() - t0;

    if (!response.ok) {
      const body = await response.text().catch(() => "");
      console.log(
        `[apify]   ❌ HTTP ${response.status} nach ${elapsed}ms: ${body.slice(0, 120)}`,
      );
      throw new Error(
        `Apify ${actor.name}: HTTP ${response.status} – ${body.slice(0, 200)}`,
      );
    }

    console.log(`[apify]   ✅ HTTP 200 nach ${elapsed}ms, lese Body...`);
    const items = (await response.json()) as Record<string, unknown>[];
    console.log(`[apify]   → ${items.length} Items erhalten`);
    return items;
  }

  // ---- Kombinierter Call (ein Actor-Aufruf für beides) ----

  async fetchVideoInfo(
    videoId: string,
    preferredLang = "de",
  ): Promise<import("../youtube/types.ts").VideoInfoResult> {
    const videoURL = `https://www.youtube.com/watch?v=${videoId}`;
    const startTime = Date.now();
    console.log(`[apify] ========== fetchVideoInfo START ==========`);
    console.log(`[apify] Video: ${videoURL}`);
    console.log(`[apify] Sprache: ${preferredLang}`);
    console.log(
      `[apify] Actor-Chain: ${ACTOR_CHAIN.length} Actors, ${ACTOR_TIMEOUT}ms Timeout pro Actor`,
    );

    // Alle Actors der Reihe nach durchprobieren
    for (let i = 0; i < ACTOR_CHAIN.length; i++) {
      const actor = ACTOR_CHAIN[i];
      const actorStart = Date.now();
      try {
        console.log(
          `[apify] --- Actor ${i + 1}/${ACTOR_CHAIN.length}: ${actor.name} ---`,
        );
        const items = await this.callActor(actor, videoURL, preferredLang);
        const actorElapsed = Date.now() - actorStart;
        console.log(
          `[apify] Actor ${actor.name} antwortete nach ${actorElapsed}ms, ${items.length} Items`,
        );

        if (items.length === 0) {
          console.log(
            `[apify] Actor ${actor.name}: Keine Items → nächster Actor`,
          );
          continue;
        }

        console.log(`[apify] Actor ${actor.name}: Ersten Item verarbeiten...`);
        console.log(
          `[apify] Item-Keys: ${Object.keys(items[0] as object).join(", ")}`,
        );

        // Metadaten aus dem ersten Item extrahieren
        const meta = this.extractMetadata(items);
        if (meta) {
          console.log(
            `[apify] Metadaten gefunden: "${meta.title}" (${meta.channelName})`,
          );
        } else {
          console.log(`[apify] Keine Metadaten extrahierbar`);
        }

        // Transcript aus dem ersten Item extrahieren
        const result = actor.extractResult(items[0]);
        let transcript: import("../youtube/types.ts").TranscriptResult | null =
          null;
        if (result && !result.error) {
          const content = result.transcriptLLM || result.transcriptText;
          if (content) {
            this.lastActorName = actor.name;
            const source = result.isAIGenerated
              ? "ai_generated"
              : result.isAutoGenerated
                ? "auto_generated"
                : "native";
            transcript = {
              content,
              language: result.language || "unknown",
              source: source as "native" | "auto_generated" | "ai_generated",
            };
            console.log(
              `[apify] ✅ Transkript gefunden: ${content.length} Zeichen (${result.language}, Quelle: ${source})`,
            );
          } else {
            console.log(
              `[apify] Actor ${actor.name}: Ergebnis hat keinen Text`,
            );
          }
        } else if (result?.error) {
          console.log(
            `[apify] Actor ${actor.name}: Ergebnis-Fehler: ${result.error}`,
          );
        } else {
          console.log(`[apify] Actor ${actor.name}: Kein Ergebnis`);
        }

        return { metadata: meta, transcript };
      } catch (e: any) {
        const actorElapsed = Date.now() - actorStart;
        console.log(
          `[apify] ❌ Actor ${actor.name} fehlgeschlagen nach ${actorElapsed}ms: ${e.message?.slice(0, 150)}`,
        );
        continue;
      }
    }

    console.log(
      `[apify] Alle ${ACTOR_CHAIN.length} Actors fehlgeschlagen, versuche AI-Fallback...`,
    );
    // AI-Fallback mit Actor #1
    try {
      const t0 = Date.now();
      console.log(
        `[apify] AI-Fallback mit ${ACTOR_CHAIN[0].name} (enableAiFallback=true)...`,
      );
      const items = await this.callActor(
        ACTOR_CHAIN[0],
        videoURL,
        preferredLang,
        true,
      );
      console.log(
        `[apify] AI-Fallback antwortete nach ${Date.now() - t0}ms, ${items.length} Items`,
      );
      if (items.length > 0) {
        const meta = this.extractMetadata(items);
        const result = ACTOR_CHAIN[0].extractResult(items[0]);
        let transcript: import("../youtube/types.ts").TranscriptResult | null =
          null;
        if (result && !result.error) {
          const content = result.transcriptLLM || result.transcriptText;
          if (content) {
            this.lastActorName = `${ACTOR_CHAIN[0].name}(ai-fallback)`;
            transcript = {
              content,
              language: result.language || "unknown",
              source: "ai_generated",
            };
            console.log(
              `[apify] ✅ AI-Fallback Transkript: ${content.length} Zeichen`,
            );
          }
        }
        return { metadata: meta, transcript };
      }
    } catch (e: any) {
      console.log(
        `[apify] ❌ AI-Fallback fehlgeschlagen: ${e.message?.slice(0, 150)}`,
      );
    }

    console.log(
      `[apify] ========== fetchVideoInfo KEINE DATEN (${Date.now() - startTime}ms) ==========`,
    );
    return { metadata: null, transcript: null };
  }

  // ---- Metadata ----

  async fetchMetadata(videoId: string): Promise<MetadataResult | null> {
    const videoURL = `https://www.youtube.com/watch?v=${videoId}`;

    // Schritt 1: Normale Actor-Chain
    for (const actor of ACTOR_CHAIN) {
      try {
        const items = await this.callActor(actor, videoURL, "");
        const meta = this.extractMetadata(items);
        if (meta) {
          this.lastActorName = actor.name;
          return meta;
        }
      } catch {
        continue;
      }
    }

    // Schritt 2: AI-Fallback mit erstem Actor
    try {
      const items = await this.callActor(ACTOR_CHAIN[0], videoURL, "", true);
      const meta = this.extractMetadata(items);
      if (meta) {
        this.lastActorName = `${ACTOR_CHAIN[0].name}(ai-fallback)`;
        return meta;
      }
    } catch {
      // nichts
    }

    return null;
  }

  private extractMetadata(
    items: Record<string, unknown>[],
  ): MetadataResult | null {
    if (items.length === 0) return null;

    const item = items[0];

    // Direktes Metadata-Format (codepoetry actor)
    const meta = item.metadata as Record<string, unknown> | undefined;
    const source = meta || item;

    const title = (source.title as string) || "";
    if (!title) return null;

    return {
      videoId: "",
      title,
      channelName: (source.channel as string) || "",
      channelUrl: (source.channel_url as string) || "",
      duration: (source.duration as number) || 0,
      thumbnailUrl: (source.thumbnail as string) || "",
      description: (source.description as string) || "",
      publishedAt: (source.upload_date as string) || "",
      tags: (source.tags as string[]) || [],
    };
  }

  // ---- Transcript ----

  async fetchTranscript(
    videoId: string,
    preferredLang = "de",
  ): Promise<TranscriptResult | null> {
    const videoURL = `https://www.youtube.com/watch?v=${videoId}`;
    let lastError: Error | null = null;

    // Schritt 1: Normale Actor-Chain
    for (const actor of ACTOR_CHAIN) {
      try {
        const items = await this.callActor(actor, videoURL, preferredLang);
        if (items.length === 0) continue;

        const result = actor.extractResult(items[0]);
        if (!result) continue;
        if (result.error) {
          lastError = new Error(`${actor.name}: ${result.error}`);
          continue;
        }

        const content = result.transcriptLLM || result.transcriptText;
        if (!content) continue;

        this.lastActorName = actor.name;
        const source = result.isAIGenerated
          ? "ai_generated"
          : result.isAutoGenerated
            ? "auto_generated"
            : "native";

        return {
          content,
          language: result.language || "unknown",
          source: source as TranscriptResult["source"],
        };
      } catch (e: any) {
        lastError = e;
        continue;
      }
    }

    // Schritt 2: AI-Fallback mit Actor #1
    try {
      const items = await this.callActor(
        ACTOR_CHAIN[0],
        videoURL,
        preferredLang,
        true,
      );
      if (items.length > 0) {
        const result = ACTOR_CHAIN[0].extractResult(items[0]);
        if (result && !result.error) {
          const content = result.transcriptLLM || result.transcriptText;
          if (content) {
            this.lastActorName = `${ACTOR_CHAIN[0].name}(ai-fallback)`;
            return {
              content,
              language: result.language || "unknown",
              source: "ai_generated",
            };
          }
        }
      }
    } catch {
      // nichts
    }

    return null;
  }
}
